name: Prisma Cloud Compute Image Scan  

on: [push]     
    
env:   
  IMAGE_NAME: smartinezc/fastapi-demo-app-nc:3.0
  
jobs:
  # Jobs are ran independently from each other, so build and scan needs to be in a single job.
  build-and-scan:
    name: Build and scan image
    runs-on: ubuntu-latest
  
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

     # - name: Download twistcli from the Prisma Cloud Compute Console
     #   run: |
     #     curl --insecure --user ${{ secrets.PCC_USER_CE }}:${{ secrets.PCC_PASS_CE }} --output ./twistcli  ${{ secrets.PCC_CONSOLE_URL_CE }}/api/v1/util/twistcli
     #     chmod a+x ./twistcli

      #- name: Build the image
      #  run: docker build -t $IMAGE_NAME .

      #- name: Scan the image
      #  run: ./twistcli images scan --address ${{ secrets.PCC_CONSOLE_URL_CE }} --user  ${{ secrets.PCC_USER_CE }} --password ${{ secrets.PCC_PASS_CE }} --details $IMAGE_NAME
